// <auto-generated />
using System;
using ChordFlow.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChordFlow.Persistence.Migrations
{
    [DbContext(typeof(ChordFlowDbContext))]
    [Migration("20260608105937_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ChordFlow.Persistence.Entities.ExerciseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgressionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RhythmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tempo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("ChordFlow.Persistence.Entities.PracticeRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PracticedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("PracticeRecords");
                });

            modelBuilder.Entity("ChordFlow.Persistence.Entities.PracticeRecordEntity", b =>
                {
                    b.HasOne("ChordFlow.Persistence.Entities.ExerciseEntity", "Exercise")
                        .WithMany("PracticeRecords")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("ChordFlow.Persistence.Entities.ExerciseEntity", b =>
                {
                    b.Navigation("PracticeRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
